# Generated by Django 4.2.11 on 2024-03-18 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantproject',
            name='project_card_entries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_project_cards', to='plantproject.plantprojectcard'),
        ),
    ]
